Gemfile, Gemfile.lock, app/models/user.rb, app/views/layouts/application.html.erb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20241029133717_devise_create_users.rb, db/migrate/20241029134824_add_details_to_users.rb, db/schema.rb, test/models/user_test.rb
Following the lecture's instruction I have installed the devise gem:
https://kitt.lewagon.com/camps/1689/lectures/05-Rails%2F06-Airbnb-Devise#
I have also modified the users' model folllowing the database schema created before
=> added basic devise configuration (also users' model modified)

app/models/booking.rb, app/models/local.rb, db/migrate/20241030140750_create_locals.rb, db/migrate/20241030141135_create_bookings.rb, db/schema.rb, test/models/booking_test.rb, test/models/local_test.rb
bookings, locals model created
=> models created! :D

app/views/layouts/application.html.erb, app/views/pages/home.html.erb
I just checked everything was there.
I added some navbar in the application: 
/home/juju/code/JuditBP/local_lens/app/views/layouts/application.html.erb
But that totally should be changed, it is only to have something there
=> homepage of Local Lens basic done

app/controllers/locals_controller.rb, app/views/layouts/application.html.erb, app/views/locals/show.html.erb, config/routes.rb, test/controllers/locals_controller_test.rb
View has 2 link_to buttons that require further development of the app before they are usable. Right now, they are only placeholders.
=> Commiting the local show action local routes and local view.

app/controllers/bookings_controller.rb, app/views/bookings/index.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb
I've created the bookings controller with just _index_ action inside. Also, I've created a basic view for bookings#index. Both files need some testing but at least some skeleton is done on both files.
=> bookings controller created -- skeleton view -- need testing

Gemfile, Gemfile.lock, app/models/user.rb, config/environments/development.rb, config/storage.yml, db/migrate/20241031105255_create_active_storage_tables.active_storage.rb, db/schema.rb
I've configurated cloudinary to store the images of our app. I modified the user model in order to be able to have an "avatar image". I've configurated the active storage as well: this will allow us to manage our images so both the users and locals will be able to have an avatar image. But the avatar image will come from the user, not the local.
=> cloudinary configurated

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_image_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_pop_ups.scss, app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, app/views/pages/styles.html.erb, config/routes.rb
Created a few button components and also created the routs of the styles route and connected google fonts to the project.
=> Added route to styles added font families, created 3 components in scss.

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/_form.html.erb, app/views/bookings/new.html.erb, config/routes.rb, db/seeds.rb
The booking process is now created. I've modified the routes.rb as well as the bookings_controller. Nevertheless, some refactor is needed due to the presence of devise gem:
The form is working:
It creates a booking properly:
I've added the validations for the bookings model and they are reflected as well in the form:
=> booking process created, needs some refactor regarding devise

app/assets/stylesheets/components/_image_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
I made the home page and also changed the look of the navbar.
=> Commiting the home page changes as well as some work on the navbar.

app/assets/stylesheets/components/_cardproduct.scss, app/assets/stylesheets/components/_image_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/_form.html.erb, app/views/bookings/new.html.erb, app/views/layouts/application.html.erb, app/views/locals/index.html.erb, app/views/pages/home.html.erb, config/routes.rb, db/seeds.rb
-created _**local_card.scs**s (and imported in components/_index.scss)
- added display-none in the available and review buttons in /components folder
- done some styling 
-
- For the future:
-  needed to add the actual pictures in de DB for future links
=> Added local show some styling

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_local_card.scss, app/views/locals/show.html.erb, db/seeds.rb
[JuditBP](https://github.com/JuditBP) commented [12 minutes ago](https://github.com/brunomoschetto/local_lens/pull/13#issue-2633273232)
-created _local_card.scss (and imported in components/_index.scss)
added display-none in the available and review buttons in /components folder
done some styling
For the future:
needed to add the actual pictures in de DB for future links
=> styling in the shows page

app/assets/stylesheets/components/_local_card.scss, app/views/layouts/application.html.erb, app/views/locals/show.html.erb
=> local show changes

config/environments/production.rb
=> some fixes in cloduinary

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_image_buttons.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/pages/_home.scss, app/assets/stylesheets/pages/_search.scss, app/controllers/locals_controller.rb, app/views/pages/home.html.erb, app/views/pages/search.html.erb
I finished the rest of the front end for the search view.
=> Commiting the search front end.

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_login.scss, app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
finished views for login and also started form styling for sign up.
=> finished views for login and also started form styling for sign up.

app/assets/stylesheets/pages/_categories.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/pages_controller.rb, app/models/local.rb, app/views/layouts/application.html.erb, app/views/locals/new.html.erb, app/views/pages/categories.html.erb, app/views/pages/home.html.erb, config/initializers/constants.rb, config/routes.rb, db/seeds.rb
- Created the categories page where the user can check 10 categories that we have so far.
- Created the categories as a global variable so we can use them in all the app, like the forms, for example, in order to create the dropdown field.
- Modified also the seeds using the new categories.
=> categories feature done!

app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/pages/_bookings_index.scss, app/assets/stylesheets/pages/_profile.scss, app/controllers/bookings_controller.rb, app/views/bookings/_local_booking.html.erb, app/views/bookings/_user_booking.html.erb, app/views/bookings/index.html.erb, app/views/pages/profile.html.erb, db/seeds.rb
updated bookings for local and revised seeds file so that tha local and user have same name.. Please run db seed after pull request
=> local bookings

app/assets/stylesheets/pages/_index.scss, app/controllers/locals_controller.rb, db/seeds.rb
Committing changes including files that where empty have been erased.
=> Commtting a few changes.

app/assets/stylesheets/pages/_bookings_index.scss, app/assets/stylesheets/pages/_index.scss, app/models/user.rb, app/views/bookings/_form.html.erb, app/views/bookings/index.html.erb
have created a toggle function
=> booking index

app/models/booking.rb, app/views/bookings/_form.html.erb
The issue is solved:
I tryed to use a gem but it doesn't work properly so I just created a method inside the booking's model.
=> The date now cannot be booked in the past anymore

app/controllers/locals_controller.rb, app/views/locals/new.html.erb, config/initializers/constants.rb, db/seeds.rb
profile pic from user to local updated
=> profilepic

app/assets/stylesheets/pages/_local_new.scss, app/assets/stylesheets/pages/_search.scss, app/views/locals/new.html.erb, app/views/pages/search.html.erb
Commiting the fixes for the local new form and the search form.
=> Commiting the fixes for the local new form and the search form.

app/controllers/locals_controller.rb, app/views/locals/index.html.erb
Instead of hide the local in the view, with the help of Lucas I created the logic in the locals_controller
So now, if you are logged in the local corresponding to this user will not be sent to the view.
=> bug solved in the controller

app/assets/stylesheets/components/_alert.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_local_card.scss, app/assets/stylesheets/components/_validation_alerts.scss, app/javascript/controllers/alerts_controller.js, app/views/layouts/application.html.erb, app/views/locals/show.html.erb, config/locales/simple_form.en.yml
Comitting the fixes to the alert style and alert pop up disappearing.
=> Comitting the fixes to the alert style and alert pop up disappearing.

app/assets/stylesheets/components/_alert.scss
I took away the red border from the pop up messages.
=> I took away the red border from the pop up messages.

app/assets/stylesheets/components/_local_card.scss, app/assets/stylesheets/pages/_bookings_form.scss, app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_review_new.scss, app/views/reviews/_form.html.erb, app/views/reviews/new.html.erb
Some forms adjustment, 🥲 with the help of Joel
star bug done
=> reviews form, and booking form adjusted
